dist: trusty
sudo: required
env: "TRAVIS_CMAKE_GENERATOR=\"Unix Makefiles\", TRAVIS_BUILD_TYPE=\"Debug\""
language: python
python:
  - "2.7"
  - "3.5"

before_install: 
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake cmake-data
    #cvxopt dependencies
    - sudo apt-get install -y liblapack3 liblapack-dev
    - sudo apt-get install -y libblas3 libblas-dev
    #install dsdp solver
    - sudo apt-get instsall -y dsdp

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
    #install iDynTree
    - git clone https://github.com/robotology/idyntree-superbuild
    - cd idyntree-superbuild
    - chmod +x ./.ci/travis-deps.sh
    - sh .ci/travis-deps.sh

    - mkdir build
    - cd build
    - export CMAKE_PREFIX_PATH=`pwd`/install
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DIDYNTREE_SUPERBUILD_USES_YARP:BOOL=OFF -DIDYNTREE_SUPERBUILD_USES_ICUB:BOOL=OFF -DIDYNTREE_SUPERBUILD_USES_PYTHON:BOOL=ON -DCODYCO_TRAVIS_CI:BOOL=ON -DNON_INTERACTIVE_BUILD:BOOL=TRUE ..
    - cmake --build . --config ${TRAVIS_BUILD_TYPE}
    - sudo cmake --build . --config ${TRAVIS_BUILD_TYPE} --target install

    #add python module dir variables to env
    - echo "`pwd`/install/lib/python2.7/site-packages" > /usr/lib/python2.7/dist-packages/iDynTree.pth
    - echo "`pwd`/install/lib/python3.5/site-packages" > /usr/lib/python3.5/dist-packages/iDynTree.pth

# command to run tests
script: pytest
