
#### excitation

excitationSimulate: 1        # simulate torques instead of using measurements to save to data files (use e.g. with Gazebo)
exciteMethod: null #'yarp'         # currently 'yarp', 'ros' or null
useDeg: 1                    # encode angles in degrees for excitation (internal and data is always in rad)

optimizeTrajectory: 1        # find new parameters with optimization or load previous params from file (if no file exists, use random)
showOptimizationGraph: 1     #display updating graph during trajectory optimization
useGlobalOptimization: 1     #do global optimization before using local refinement (does not use initial values)
globalOptIterations: 5
localOptIterations: 1        #how many optimizer iterations to use. this is not necessarily equal to function calls (~50 times of this)
maxFun: 250                  #limit objective function evaluations to this value (not used currently)
min_tol_constr: 0.01         # threshold for being within constraints (only used for display)

# initial values to start optimization from (if using global opt not really important)
trajectorySpeed: 0.4         #set this as high as possible without violating constraints (see output after start)
trajectoryPulseInit: 0.75    #determines length of one period of trajectory (smaller=longer)
trajectoryPulseMin:  0.5
trajectoryPulseMax:  1.5
trajectoryCoeffMin: -0.5     #determines in which range the chosen params have to be (smaller=lower vel)
trajectoryCoeffMax:  0.5
trajectoryAngleMin: -25.0    #determines the range in which the pulsation center for each joint will be (in degrees)
trajectoryAngleMax:  25.0

# manual angle limits: pairs of upper and lower (in degrees). put in null to use values from URDF
# (or leave completely empty)
ovr_pos_limit:
    - null
    - null 
    - null
    - null
    - null
    - null
    - null

#### identification

# fixed or floating-base dynamics
floating_base: 1
base_link_name: 'Waist'
#if set to 1, also add <baseLinkDynamics/> as first rows to regressor definition xml

# simulate torques from target values, don't use both
iDynSimulate: 0 # simulate torque for measured angles etc using idyntree (instead of reading from data)
addNoise: 0 #0.05  #additional percentage of zero-mean white noise for simulated or measured torques

# almost zero threshold for QR, SVD and other things
min_tol: 0.0001

## data selection

# determine number of samples to use
# (Khalil recommends about 500 times number of parameters to identify...)
start_offset: 0    #how many samples from the beginning of the (first) measurement are skipped
skip_samples: 0    #how many values to skip before using the next sample

# whether only "good" data is being selected or simply all is used (selected by condition number)
selectBlocksFromMeasurements: 0
block_size: 250  # needs to be at least as much as parameters so regressor is square or higher

removeNearZero: 1  #remove samples that have almost zero velocity
minVel: 0.02       #minimum mean velocity for a sample to be taken (rad/s)

## use constrained SDP to solve OLS

# constrain std params to physical consistent space to only achieve physical consistent parameters
# (currently this also does the estimation, so previously selecting another method has no effect)
# if only torque estimation is desired, not using this self.option might give a better model
# accuracy with approriate parameters
useConsistencyConstraints: 1

# constrain parameters for links more than a certain condition number to the a priori values
# (to prevent very big changes for parameters that are not expressed in the data)
noChange: 1
noChangeThresh: 200

# restrict COM to smallest enclosing box of STL Mesh (taken from <visual> in URDF)
restrictCOMtoHull: 1
# set extra scaling for mesh (e.g. if it is clear that COM will not be at outer border of
# geometry or that initial CAD data is too large)
hullScaling: 1.0

# constrain overall mass
limitOverallMass: 0
# if overall mass is set, limit to this value. If null, limit to overall a priori mass +- 30%
limitMassVal: null #16

# enforce the same upper limit for each link mass
limitMassValPerLink: null #3

# or enforce staying around the a priori masses (only set this or a combination of the other
# two mass limiting self.options to prevent constraint conflicts!)
limitMassToApriori: 1
limitMassAprioriBoundary: 0.5     #allowed change of CAD value in both +- directions (1.0 = 100%)

# whether to take out masses to be identified because they are e.g.
# well known or introduce problems
# (essential params or when using feasability constraints)
dontIdentifyMasses: 0

## other forms of OLS

# use previously known CAD parameters to identify parameter error, estimates parameters closer to
# known ones (taken from URDF file)
# for some methods, this gives parameters that are more likely to be consistent
# (no effect for SDP constrained solutions)
useAPriori: 0

# identify and use direct standard with essential parameters
useEssentialParams: 0

# whether to include linear dependent columns in essential params or not
useDependents: 1

# use weighted least squares(WLS) instead of ordinary least squares
# needs small condition number, otherwise might amplify some parameters too much as the
# covariance estimation can be off (also assumes that error is zero mean and normal
# distributed)
useWLS: 0

# whether to filter the regressor columns (cutoff frequency is system dependent)
# mostly not improving results
filterRegressor: 0

## output and debugging

createPlots: 1               #create or show plots of measurements and estimated values
outputModule: 'html'         #how to output plots and other stuff ['matplotlib', 'html]

# self.options for console output
showMemUsage: 0              #print used memory for different variables
showTiming: 0                #show times various steps have taken
showRandomRegressor: 0       #show 2d plot of random regressor
showErrorHistogram: 0        #show estimation error distribution
showEssentialSteps: 0        #stop after every reduction step and show values
outputBarycentric: 0         #output all values in barycentric (e.g. urdf) form
showStandardParams: 1        #display a list of identified standard params
showBaseParams: 1            #display a list of identified base params (if appliable)
verbose: 1                   #show more messages

# which parameters to use when estimating torques for validation. Set to one of
# ['base', 'std', 'std_direct', 'urdf
estimateWith: 'std'
